server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://config-server:8888"
management:
  endpoints:
    web:
      exposure:
        include: health,info

# spring:
#   cloud:
#     gateway:
#       routes:
#         - id: auth
#           uri: http://auth-service:8080
#           predicates:
#             - Path=/auth/**
#           filters:
#             - StripPrefix=1

#         - id: orders
#           uri: http://orders-service:8080
#           predicates:
#             - Path=/orders/**
#           filters:
#             - StripPrefix=1

#         - id: payments
#           uri: http://payments-service:8080
#           predicates:
#             - Path=/payments/**
#           filters:
#             - StripPrefix=1

#         - id: analytics
#           uri: http://analytics-service:8080
#           predicates:
#             - Path=/analytics/**
#           filters:
#             - StripPrefix=1

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info
        
# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG
#     reactor.netty.http.client: DEBUG
#     reactor.netty.http.server: DEBUG
